name: app_localizations
description: App localizations for Flutter
version: 1.0.0
homepage: fman.ge

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  hive:
  hive_flutter: ^1.1.0
  version:

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.21.1
  mocktail: ^0.3.0
